[package]
name = "hzospal"
version = "0.1.0"
edition = "2024"

[dependencies]
btleplug = "0.11.8"
crossterm = "0.29.0"
futures = "0.3.31"
prost = "0.14.3"
ratatui = "0.30.0"
tokio = { version = "1.49.0", features = ["full"] }
uuid = "1.19.0"

[build-dependencies]
prost-build = "0.14.3"
